FROM node:18-bullseye

# Set the working directory
WORKDIR /app

# Copy package files to cache dependencies
COPY package.json .
COPY package-lock.json .

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    build-essential \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js dependencies
RUN npm install
# 
# Command to serve the Gatsby site
# CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "dev"]